import Link from "next/link";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import Header from "@/components/menus/header";

import "./tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next pages",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => (
  <html lang="en">
    <body className={inter.className}>
      <header className="flex items-center justify-between px-4 py-4 border-b-2">
        <Link href="/">Tyler Scott</Link>
        <Header />
      </header>
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;
